spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    driver-class-name: org.postgresql.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: never
      schema-locations:
        - file:ddl.sql
      data-locations:
        - file:data/sellers.sql
        - file:data/brands.sql
        - file:data/categories.sql
        - file:data/tags.sql
        - file:data/products.sql
        - file:data/product_options.sql
        - file:data/product_extended.sql
        - file:data/users.sql
        - file:data/reviews.sql

server:
  port: 8081